name: advanced_pdf_viewer
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.advanced_pdf_viewer
        pluginClass: AdvancedPdfViewerPlugin
      ios:
        pluginClass: AdvancedPdfViewerPlugin


  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/arial.ttf
